### ISSUE TITLE
setp2: index out of range, 1.3.0, 50 files

### ISSUE THREAD

**Issue by some2014** [peterljq/OpenMMD#27]
尊敬的作者，您好！
open pose版本1.3.0， Json文件夹仅有50个文件 一样出错
运行到第二步 3d-pose-baseline-vmd，list index out of range

DEBUG:__main__:FLAGS.person_idx=1
INFO:__main__:start reading data
DEBUG:__main__:reading test_000000000000_keypoints.json
Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 484, in <module>
    tf.app.run()
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/openpose_3dpose_sandbox_vmd.py", line 283, in main
    smoothed = read_openpose_json(now_str, idx, subdir)
  File "src/openpose_3dpose_sandbox_vmd.py", line 74, in read_openpose_json
    _tmp_data = data["people"][idx]["pose_keypoints_2d"]
IndexError: list index out of range

**Comment by some2014** [comment]
使用的是素材是自带的跳舞的女孩 ，sample.mkv ，23秒

**Comment by peterljq** [comment]
Please refer to some similar issues and see if they help: #10 and #18
